[package]
name = "red-packet"
version = "0.2.0"
license = "Apache-2.0"

[dependencies]
#AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "a5ac706f74c3b5088649e744b76ec6ed32635c0d" }
AptosFramework = { local = "./aptos-core/aptos-move/framework/aptos-framework" }

[addresses]
RedPacket = "_"

[dev-addresses]
RedPacket = "0x123"
