[package]
name = "red-packet"
version = "0.1.0"
authors = "ComingChat Authors"
license = "Apache-2.0"

[dependencies]
#AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "b718154c93b3556658c8c06341be0cf47957188c" }
#AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "b718154c93b3556658c8c06341be0cf47957188c" }
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "../../../aptos-core/aptos-move/framework/aptos-stdlib" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
RedPacket = "_"

[dev-addresses]
RedPacket = "0x123"
