[package]
name = "red-packet"
version = "0.2.0"
license = "Apache-2.0"
upgrade_policy = "compatible"

#[dependencies.AptosFramework]
#git = 'https://github.com/aptos-labs/aptos-core.git'
#rev = 'main'
#subdir = 'aptos-move/framework/aptos-framework'
[dependencies]
AptosFramework = { local = "./aptos-core/aptos-move/framework/aptos-framework" }

[addresses]
RedPacket = "_"

[dev-addresses]
RedPacket = "0x123"
